# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_contact', '0002_auto_20160810_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_contact_contact', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='form_layout',
            field=models.CharField(choices=[(b'cmsplugin_contact.forms.ContactForm', 'default')], help_text='Choice the layout of contact form', max_length=255, verbose_name='Form Layout'),
        ),
    ]
