# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_contact', '0003_auto_20161107_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='submit',
            new_name='submit_text',
        ),
    ]
