# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_contact', '0004_auto_20180630_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='recaptcha_size',
            field=models.CharField(choices=[(b'normal', 'Normal'), (b'compact', 'Compact')], default=b'normal', max_length=20, verbose_name='ReCAPTCHA size'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='form_layout',
            field=models.CharField(choices=[(b'cmsplugin_contact.forms.ContactForm', 'default')], help_text='Choose the layout of contact form', max_length=255, verbose_name='Form Layout'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='recaptcha_theme',
            field=models.CharField(choices=[(b'light', 'Light'), (b'dark', 'Dark')], default=b'light', max_length=20, verbose_name='ReCAPTCHA theme'),
        ),
    ]
